version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_note
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - C:/Users/letha/OneDrive/Documents/Important/P9/db_note:/data/db
    ports:
      - "27027:27027"
    command: ["mongod", "--port", "27027", "--bind_ip", "0.0.0.0"]